In [1]:
import numpy
# import numpy as np
# from numpy import arange
# from numpy import *
# n = numpy.arange(11)
# print(type(n))
# print(n)
# print(n[0])


# example
# n = numpy.arange(12)
# d = n.reshape(3,4) # 3 -> rows or 4 -> cols
# print(type(d))
# print(d)

#example 2d
# n = numpy.arange(12).reshape(4,3)
# print(n)


# example 3d
# n = numpy.arange(24).reshape(1,6,4) # 3-> rows or 4 -> cols
# print(n)


# example split # 2,5,8,11 -> print
# n = numpy.arange(12).reshape(4,3)
# print(n)
# print(n[0:4:,2]) # first row or second cols
# print(n[0:4,2:4]) # first row or second cols
# print(n[:,-1])

#example split # 4,7 -> print
n = numpy.arange(12).reshape(4,3)
print(n)
print(n[1:3,1:2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4]
 [7]]


creating array from list

1. 1d
2. 2d

In [2]:
# import numpy as np
# # list 1d
# l = [1,2,3]
# print(l)

# # array 1d
# arr = np.array(l)
# print(arr)

# 2d example

import numpy as np
# 2d list
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0]) # [1,2,3] -> 1row
print(l[0][0]) # [1,2,3] -> 1row -> first element -> 1

# question list value 4 -> 100
l[1][0] = 100
print(l[1])

# 2d array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0]) # [1,2,3] -> 1 row
print(arr[0][0]) # [1,2,3] -> 1row -> first element -> 1

# question array value 4 -> 100
arr[1][0] = 100
print(arr[1])
     

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
[100, 5, 6]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[100   5   6]


list vs numpy array

1. Example of multi with list and array
2. time comparsion
3. zeros (3,4)
4. ones (2,3)
5. full ((2,2),7)
6. random (2,3)
7. range (0,10,2)

In [3]:
# list
l = [1,2,3]
lm = l*2
print(lm)

# array
import numpy as np
arr = np.array(l)
arrM = arr*2
print(arrM)
     

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [4]:
# comparsion
# array running timing less than list
import numpy as np
import time

# list range(10) -> 0 to 9
start = time.time()
l = [i*500 for i in range(1000000)]
print("list output:",time.time() - start) # 0.06

# array
start = time.time()
arr = np.array(1000000)*500
print("array output:",time.time() - start) # 0.0001


list output: 0.06641101837158203
array output: 0.00019049644470214844


In [5]:
# zeros array 1d
import numpy as np
arr =  np.zeros(5)
print(arr)

# zeros array 2d
arr1 = np.zeros((3,4))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# ones array 1d
import numpy as np
arr = np.ones(5)
print(arr)
# ones array 2d
arr1 = np.ones((3,4))
print(arr1)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
import numpy as np
# question zeros -> 2d array -> 10
arr = np.zeros((2,3))+10
print(arr)
# question ones -> 2d array -> 5
arr1 = np.ones((2,3))+5
print(arr1)

[[10. 10. 10.]
 [10. 10. 10.]]
[[6. 6. 6.]
 [6. 6. 6.]]


In [8]:
# full for 1d
import numpy as np
arr = np.full((3),5)
print(arr)


# full for 2d
import numpy as np
arr1 = np.full((2,3),5)
print(arr1)


# question help of zeros -> 2d -> 6
# question help of full -> 2d -> 1

[5 5 5]
[[5 5 5]
 [5 5 5]]


In [10]:
#random for 1d 0 -> 1
import numpy as np
arr = np.random.random(5)
print(arr)

# random for 2d 0-> 1
arr1 = np.random.random((2,3))
print(arr1)

[0.90560665 0.88605699 0.91777439 0.18132437 0.17792656]
[[0.47685015 0.8888456  0.14958886]
 [0.46734829 0.016261   0.17621905]]


In [11]:
#arange for 1d
import numpy as np
arr = np.arange(5)
print(arr)

#arange for 1d || to convert into 2d -> reshape
arr1 = np.arange(0,10,2) # start,stop,step
print(arr1)

[0 1 2 3 4]
[0 2 4 6 8]


Vector,matrix,tensor

1. vector (1d)
2. matrix (2d)
3. tensor (3d)

In [12]:
import numpy as np
# vector 1d list
l = [1,2,3]
print(l)
#vector 1d array
arr = np.array(l)
print(arr)

#matrix 2d list
l = [[1,2,3],[4,5,6]]
print(l)
#matrix 2d array
arr = np.array(l)
print(arr)

#tensor 3d list
l = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(l)
#tensor 3d array
arr = np.array(l)
print(arr)

[1, 2, 3]
[1 2 3]
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

1. shape
2. dimension
3. size
4. dtype

In [13]:
# array
import numpy as np
arr = np.arange(12) # 1d
# arr = np.arange(12).reshape(3,4) # 3 X 4 => 12  # 2d
print("shape: ",arr.shape)
print("shape: ",np.shape(arr))
print("dimension: ",np.ndim(arr))
print("size: ",np.size(arr))
print("datatype: ",arr.dtype)
     

shape:  (12,)
shape:  (12,)
dimension:  1
size:  12
datatype:  int64
