Array reshaping
1. reshape()
2. flatten() -> crete copy
3. ravel() -> return original 
4. trnspose


In [10]:
# reshape array
import numpy as np

arr = np.arange(12)  #12 -> 3*4 || 12 -> 4*3
up_arr = np.reshape(arr, (3, 4))

print(up_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
#example2d
import numpy as np
arr1 = np.arange(24)

up_arr1 = np.reshape(arr1,(12*2))

print(up_arr1)

#example3d
arr2 = np.arange(24)
up_arr2 = np.reshape(arr2,(3*2*4))
print(up_arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [12]:
#example 2d 
import numpy as np

arr = np.arange(6)
arr_2d = arr.reshape(2, 3)

print(arr_2d)

#example 3d
import numpy as np

arr = np.arange(8)
arr_3d = arr.reshape(2, 2, 2)

print(arr_3d)

[[0 1 2]
 [3 4 5]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [18]:
#flatten 
import numpy as np
arr = np.arange(12).reshape(3, 4)
print(arr)
up_arr = arr.flatten
print(up_arr)

#example 3d
arr1 = np.arange(24).reshape(3, 2, 4)
print(arr1)
up_arr1 = arr1.flatten()
print(up_arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<built-in method flatten of numpy.ndarray object at 0x7fd8db3662b0>
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
#ravel -> works as original array
import numpy as np 
#example 2d
arr = np.arange(14).reshape(7 , 2)
print(arr)
up_arr = arr.ravel()
print(up_arr)




[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [22]:
#transpose
import numpy as np
arr = np.arange(12).reshape(3, 4)   
print(arr)
up_arr = arr.transpose()
print(up_arr)

#example 3d
import numpy as np

arr = np.arange(8).reshape(2, 2, 2)

print("Original Array:")
print(arr)

up_arr = arr.transpose()

print("\nTranspose Array:")
print(up_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Original Array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Transpose Array:
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


numpy array operation 
1. slicing for 1d,2d,3d


In [33]:
#slicing for 1d 
import numpy as np
arr = np.arange(11)
print(arr)
up_arr = arr[:3]
print(up_arr)

#slicing for 2d
import numpy as np
arr1 = np.arange(16).reshape(8,2)
print(arr1)

#slicing for 3d -> arange(24) ->0,23
import numpy as np

arr = np.arange(24).reshape(2,3,4)

print(arr[0,0,0], arr[1,2,3])

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
0 23


looping with numpy
1. while loop 
2. for loop


In [48]:
#while loop 
#while loop for 1d
import numpy as np
arr = np.arange(12)
i = 0
while i <len(arr):
    print(arr[i], end = " ")
    i += 1

#while loop for 2d
import numpy as np
arr1 = np.arange(12).reshape(3, 4)
i = 0
while i < len(arr1):
    j = 0
    while j < len(arr1[i]):
          print(arr1[i][j], end = " ")
          j += 1
    print("\n")      
    i += 1   
    
    
    #   while loop for 3d
    import numpy as np

arr = np.arange(24).reshape(2,3,4)

i = 0
while i < 2:
    j = 0
    while j < 3:
        k = 0
        while k < 4:
            print(arr[i][j][k], end=" ")
            k += 1
        print()
        j += 1
    print()
    i += 1


0 1 2 3 4 5 6 7 8 9 10 11 0 1 2 3 

4 5 6 7 

8 9 10 11 

0 1 2 3 
4 5 6 7 
8 9 10 11 

12 13 14 15 
16 17 18 19 
20 21 22 23 

